set(_CATKIN_CURRENT_PACKAGE "epipolar_pkg")
set(epipolar_pkg_VERSION "0.0.0")
set(epipolar_pkg_MAINTAINER "arindam <arindam@todo.todo>")
set(epipolar_pkg_PACKAGE_FORMAT "1")
set(epipolar_pkg_BUILD_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "nav_msgs" "roscpp" "sensor_msgs" "tf" "trajectory_msgs")
set(epipolar_pkg_BUILD_EXPORT_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "nav_msgs" "roscpp" "sensor_msgs" "tf" "trajectory_msgs")
set(epipolar_pkg_BUILDTOOL_DEPENDS "catkin")
set(epipolar_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(epipolar_pkg_EXEC_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "nav_msgs" "roscpp" "sensor_msgs" "tf" "trajectory_msgs")
set(epipolar_pkg_RUN_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "nav_msgs" "roscpp" "sensor_msgs" "tf" "trajectory_msgs")
set(epipolar_pkg_TEST_DEPENDS )
set(epipolar_pkg_DOC_DEPENDS )
set(epipolar_pkg_URL_WEBSITE "")
set(epipolar_pkg_URL_BUGTRACKER "")
set(epipolar_pkg_URL_REPOSITORY "")
set(epipolar_pkg_DEPRECATED "")